
## ----------------------------------------------------------------------------
##
## TucuLicense Makefile
##
## ----------------------------------------------------------------------------

NAME := tuculicense
TYPE := APP

SOURCES := main.cpp

INCLUDES := ../../libs/spdlog-master-20170622/include \
            ../../libs/date/include \
            ../../libs/botan-2.1.0/build/include

LIBS := tucucommon botan
EXTLIBS :=
DEFINES :=

include $(TUCUXI_ROOT)/make/rules.mak
