
## ----------------------------------------------------------------------------
##
## TucuLicense Makefile
##
## ----------------------------------------------------------------------------

NAME := tuculicense
TYPE := LIB

SOURCES := licensegenerator.cpp \
           main.cpp

INCLUDES := ../../libs/spdlog-master-20170622/include \
            ../../libs/date-master-20170711 \
            ../../libs/botan-2.1.0/build/include

LIBS := 
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
