
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucore
TYPE := LIB

SOURCES := concentrationcalculator.cpp \
           intakeintervalcalculator.cpp \
           cachedlogarithms.cpp \
           onecompartmentbolus.cpp \
           onecompartmentextra.cpp \
           onecompartmentinfusion.cpp \
           twocompartmentbolus.cpp \
           twocompartmentextra.cpp \
           twocompartmentinfusion.cpp \
           threecompartmentbolus.cpp \
           threecompartmentextra.cpp \
           threecompartmentinfusion.cpp \
           intakeextractor.cpp \
           dosage.cpp \
           operation.cpp \
           hardcodedoperation.cpp
INCLUDES := . \
            ../../libs/eigen-3.3.2 \
            ../../libs/boost-1.63.0 \
            ../../libs/date-master-20170711 \
            ../../libs/spdlog-master-20170622/include
LIBS := 
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
