
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCore
TYPE := LIB

SOURCES := concentrationcalculator.cpp \
           intakeintervalcalculator.cpp \
           cachedlogarithms.cpp \
           onecompartmentbolus.cpp \
           onecompartmentextra.cpp
INCLUDES := . \
            ..\..\Libs\eigen \
            ..\..\Libs\boost
LIBS := 
EXTLIBS := 
DEFINES := TUCUCORE_LIBRARY

include $(TUCUXI_ROOT)/Make/Rules.mak
