
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCore
TYPE := LIB

SOURCES := concentrationcalculator.cpp \
           intakeintervalcalculator.cpp \
           cachedlogarithms.cpp \
           onecompartmentbolus.cpp \
           onecompartmentextra.cpp
INCLUDES := . \
            ../../Libs/eigen-3.3.2 \
            ../../Libs/boost-1.63.0
LIBS := 
EXTLIBS := 
DEFINES := TUCUCORE_LIBRARY

include $(TUCUXI_ROOT)/Make/Rules.mak
