
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCommon
TYPE := TEST

SOURCES := tests.cpp
INCLUDES := ../../Libs/fructose-1.3/fructose/include

LIBS := TucuCommon
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/Make/Rules.mak
