
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCommon
TYPE := TEST

SOURCES := tests.cpp
INCLUDES := ../../libs/fructose-1.3/fructose/include

LIBS := TucuCommon
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
