
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucommon
TYPE := TEST

SOURCES := tests.cpp

INCLUDES := ../../libs/fructose/include \
            ../../libs/spdlog/include \
            ../../libs/date/include \
            ../../libs/rapidxml \
            ../../libs/eigen-3.3.2 \
            ../../libs/botan-2.19.3/build/include

LIBS := tucucommon botan
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
