
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucuvalidator
TYPE := APP

SOURCES := tucuvalidator.cpp

INCLUDES := . \
            ../../libs/eigen \
            ../../libs/spdlog/include \
            ../../libs/date/include \
            ../../libs/cxxopts/include

LIBS := tucuquery tucucommon tucucore botan
EXTLIBS :=
DEFINES :=

include $(TUCUXI_ROOT)/make/rules.mak
