
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tinyjs
TYPE := LIB

SOURCES := TinyJS.cpp \
           TinyJS_Functions.cpp \
           TinyJS_MathFunctions.cpp \
           TinyJS_SyntaxTree.cpp
INCLUDES :=             

LIBS := 
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
