
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucrypto
TYPE := TEST

SOURCES := tests.cpp
INCLUDES := ../../libs/fructose-1.3/fructose/include \
            ../../libs/spdlog-master-20170622/include \
            ../../libs/date/include \
            ../../libs/rapidxml-1.13 \
            ../../libs/eigen-3.3.2 \
            ../../libs/botan-2.19.3/build/include

LIBS := tucucommon botan
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
