
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucuquery
TYPE := LIB

# Let's keep it in alphabetical order
SOURCES := \
           administrativedata.cpp \
           computingquery.cpp \
           computingqueryresponse.cpp \
           computingqueryresponsexmlexport.cpp \
           computingresponseexport.cpp \
           fullsample.cpp \
           parametersdata.cpp \
           querycomputer.cpp \
           querydata.cpp \
           queryimport.cpp \
           querylogger.cpp \
           querytocoreextractor.cpp \
           requestdata.cpp

INCLUDES := . \
            ../../libs/eigen-3.3.2 \
            ../../libs/boost-1.83.0 \
            ../../libs/date/include \
            ../../libs/spdlog/include
LIBS :=
EXTLIBS :=
DEFINES :=

include $(TUCUXI_ROOT)/make/rules.mak
