
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucuquery
TYPE := LIB

# Let's keep it in alphabetical order
SOURCES := \
           administrativedata.cpp \
           computingresponseexport.cpp \
           computingresponsexmlexport.cpp \
		   parametersdata.cpp \
		   query.cpp \
		   queryimport.cpp \
		   querytocoreextractor.cpp \
		   requestdata.cpp

INCLUDES := . \
            ../../libs/eigen-3.3.2 \
            ../../libs/boost-1.63.0 \
            ../../libs/date-master-20170711 \
            ../../libs/spdlog-master-20170622/include
LIBS :=
EXTLIBS :=
DEFINES :=

include $(TUCUXI_ROOT)/make/rules.mak
