
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCommon
TYPE := LIB

SOURCES := componentmanager.cpp
INCLUDES := .

LIBS := 
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
