
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucommon
TYPE := LIB

SOURCES := componentmanager.cpp \
           logger.cpp \
           utils.cpp \
           jsengine.cpp \
           duration.cpp \
           timeofday.cpp \
           datetime.cpp
INCLUDES := ../../libs/spdlog-master-20170622/include \
            ../../libs/tiny-js-master-20170629 \
            ../../libs/date-master-20170711

LIBS := tinyjs
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
