
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucore
TYPE := TEST

SOURCES := tests.cpp
INCLUDES := ../../libs/fructose-1.3/fructose/include \
            ../../libs/spdlog-master-20170622/include \
            ../../libs/eigen-3.3.2 \
            ../../libs/boost-1.83.0 \
            ../../libs/date/include
            
LIBS := tucucommon tucucore botan
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
