
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucore
TYPE := TEST

SOURCES := tests.cpp

INCLUDES := ../../libs/fructose/include \
            ../../libs/spdlog/include \
            ../../libs/eigen \
            ../../libs/boost-1.83.0 \
            ../../libs/date/include
            
LIBS := tucucommon tucucore botan
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
