
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCli
TYPE := APP

SOURCES := tucucli.cpp 
INCLUDES := . \
            ../../libs/eigen-3.3.2 \
            ../../libs/spdlog-master-20170622\include
LIBS := TucuCore
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
