
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCli
TYPE := APP

SOURCES := tucucli.cpp 
INCLUDES := . \
            ..\..\Libs\eigen
LIBS := TucuCore
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/Make/Rules.mak
