
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := TucuCli
TYPE := APP

SOURCES := tucucli.cpp 
INCLUDES := . \
            ../../Libs/eigen-3.3.2
LIBS := TucuCore
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/Make/Rules.mak
