
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucucli
TYPE := APP

SOURCES := tucucli.cpp \
           clicomputer.cpp

INCLUDES := . \
            ../../libs/eigen-3.3.2 \
            ../../libs/spdlog-master-20170622/include \
            ../../libs/date/include \
			../../libs/cxxopts

LIBS := tucuquery tucucommon tucucore botan
EXTLIBS :=
DEFINES :=

include $(TUCUXI_ROOT)/make/rules.mak
