
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tuculicense
TYPE := TEST

SOURCES := tests.cpp

INCLUDES := ../../libs/fructose/include \
            ../../libs/spdlog/include \
            ../../libs/date/include \
            ../../libs/botan/build/include

LIBS := tucucommon tuculicense botan
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
