
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tuculicense
TYPE := TEST

SOURCES := tests.cpp
INCLUDES := ../../libs/fructose/include \
            ../../libs/spdlog-master-20170622/include \
            ../../libs/date/include \
            ../../libs/botan-2.19.3/build/include

LIBS := tucucommon tuculicense botan
EXTLIBS := 
DEFINES := 

include $(TUCUXI_ROOT)/make/rules.mak
