
## ----------------------------------------------------------------------------
##
## TucuMath Makefile
##
## ----------------------------------------------------------------------------

NAME := tucudrugfilechecker
TYPE := APP

SOURCES := tucudrugfilechecker.cpp

INCLUDES := . \
            ../../libs/eigen-3.3.2 \
            ../../libs/spdlog/include \
            ../../libs/date/include \
            ../../libs/cxxopts

LIBS := tucuquery tucucommon tucucore botan
EXTLIBS :=
DEFINES :=

include $(TUCUXI_ROOT)/make/rules.mak
