
HEADERS += \
    $$PWD/../../src/tucucore/drugmodel/drugmodel.h \
    $$PWD/../../src/tucucore/cachedexponentials.h \
    $$PWD/../../src/tucucore/concentrationcalculator.h \
    $$PWD/../../src/tucucore/cyclestatisticscalculator.h \
    $$PWD/../../src/tucucore/definitions.h \
    $$PWD/../../src/tucucore/dosage.h \
    $$PWD/../../src/tucucore/intakeevent.h \
    $$PWD/../../src/tucucore/intakeintervalcalculator.h \
    $$PWD/../../src/tucucore/intakeextractor.h \
    $$PWD/../../src/tucucore/onecompartmentbolus.h \
    $$PWD/../../src/tucucore/onecompartmentextra.h \
    $$PWD/../../src/tucucore/parameter.h \
    $$PWD/../../src/tucucore/timedevent.h \
    $$PWD/../../src/tucucore/operation.h \
    $$PWD/../../src/tucucore/onecompartmentinfusion.h \
    $$PWD/../../src/tucucore/threecompartmentbolus.h \
    $$PWD/../../src/tucucore/threecompartmentextra.h \
    $$PWD/../../src/tucucore/threecompartmentinfusion.h \
    $$PWD/../../src/tucucore/twocompartmentbolus.h \
    $$PWD/../../src/tucucore/twocompartmentextra.h \
    $$PWD/../../src/tucucore/twocompartmentinfusion.h \
    $$PWD/../../src/tucucore/corecomponent.h \
    $$PWD/../../src/tucucore/covariateextractor.h \
    $$PWD/../../src/tucucore/idatamodelservices.h \
    $$PWD/../../src/tucucore/iprocessingservices.h \
    $$PWD/../../src/tucucore/parametersextractor.h \
    $$PWD/../../src/tucucore/residualerrormodel.h \
    $$PWD/../../src/tucucore/sampleextractor.h \
    $$PWD/../../src/tucucore/target.h \
    $$PWD/../../src/tucucore/targetextractor.h \
    $$PWD/../../src/tucucore/pkmodel.h \
    $$PWD/../../src/tucucore/intaketocalculatorassociator.h \
    $$PWD/../../src/tucucore/hardcodedoperation.h \
    $$PWD/../../src/tucucore/onecompartmentinfusion_yta.h \
    $$PWD/../../src/tucucore/montecarlopercentilecalculator.h \
    $$PWD/../../src/tucucore/deriv.h \
    $$PWD/../../src/tucucore/likelihood.h \
    $$PWD/../../src/tucucore/minimize.h \
    $$PWD/../../src/tucucore/aposteriorietascalculator.h \
    $$PWD/../../src/tucucore/operablegraphmanager.h \
    $$PWD/../../src/tucucore/drugdefinitions.h \
    $$PWD/../../src/tucucore/drugmodel/analyte.h \
    $$PWD/../../src/tucucore/drugmodel/activesubstance.h \
    $$PWD/../../src/tucucore/drugmodel/drugmodeldomain.h \
    $$PWD/../../src/tucucore/drugmodel/formulationandroute.h \
    $$PWD/../../src/tucucore/drugmodel/parameterdefinition.h \
    $$PWD/../../src/tucucore/drugmodel/targetdefinition.h \
    $$PWD/../../src/tucucore/drugmodel/validdose.h \
    $$PWD/../../src/tucucore/drugmodel/validduration.h \
    $$PWD/../../src/tucucore/sampleevent.h \
    $$PWD/../../src/tucucore/targetevent.h \
    $$PWD/../../src/tucucore/drugtreatment/sample.h \
    $$PWD/../../src/tucucore/drugtreatment/target.h \
    $$PWD/../../src/tucucore/drugtreatment/drugtreatment.h \
    $$PWD/../../src/tucucore/processingservice/processingrequest.h \
    $$PWD/../../src/tucucore/processingservice/processingresponse.h \
    $$PWD/../../src/tucucore/processingservice/iprocessingservice.h \
    $$PWD/../../src/tucucore/processingservice/processingtrait.h \
    $$PWD/../../src/tucucore/drugmodel/covariatedefinition.h \
    $$PWD/../../src/tucucore/drugtreatment/patientcovariate.h \
    $$PWD/../../src/tucucore/covariateevent.h

SOURCES += \
    $$PWD/../../src/tucucore/drugmodel/drugmodel.cpp \
    $$PWD/../../src/tucucore/cachedexponentials.cpp \
    $$PWD/../../src/tucucore/concentrationcalculator.cpp \
    $$PWD/../../src/tucucore/cyclestatisticscalculator.cpp \
    $$PWD/../../src/tucucore/intakeintervalcalculator.cpp \
    $$PWD/../../src/tucucore/intakeextractor.cpp \
    $$PWD/../../src/tucucore/dosage.cpp \
    $$PWD/../../src/tucucore/onecompartmentbolus.cpp \
    $$PWD/../../src/tucucore/onecompartmentextra.cpp \
    $$PWD/../../src/tucucore/operation.cpp \
    $$PWD/../../src/tucucore/onecompartmentinfusion.cpp \
    $$PWD/../../src/tucucore/threecompartmentbolus.cpp \
    $$PWD/../../src/tucucore/threecompartmentextra.cpp \
    $$PWD/../../src/tucucore/threecompartmentinfusion.cpp \
    $$PWD/../../src/tucucore/twocompartmentbolus.cpp \
    $$PWD/../../src/tucucore/twocompartmentextra.cpp \
    $$PWD/../../src/tucucore/twocompartmentinfusion.cpp \
    $$PWD/../../src/tucucore/corecomponent.cpp \
    $$PWD/../../src/tucucore/covariateextractor.cpp \
    $$PWD/../../src/tucucore/parameter.cpp \
    $$PWD/../../src/tucucore/parametersextractor.cpp \
    $$PWD/../../src/tucucore/sampleextractor.cpp \
    $$PWD/../../src/tucucore/targetextractor.cpp \
    $$PWD/../../src/tucucore/pkmodel.cpp \
    $$PWD/../../src/tucucore/intaketocalculatorassociator.cpp \
    $$PWD/../../src/tucucore/hardcodedoperation.cpp \
    $$PWD/../../src/tucucore/montecarlopercentilecalculator.cpp \
    $$PWD/../../src/tucucore/likelihood.cpp \
    $$PWD/../../src/tucucore/aposteriorietascalculator.cpp \
    $$PWD/../../src/tucucore/operablegraphmanager.cpp \
    $$PWD/../../src/tucucore/residualerrormodel.cpp \
    $$PWD/../../src/tucucore/drugmodel/analyte.cpp \
    $$PWD/../../src/tucucore/drugmodel/activesubstance.cpp \
    $$PWD/../../src/tucucore/drugmodel/drugmodeldomain.cpp \
    $$PWD/../../src/tucucore/drugmodel/formulationandroute.cpp \
    $$PWD/../../src/tucucore/drugmodel/parameterdefinition.cpp \
    $$PWD/../../src/tucucore/drugmodel/targetdefinition.cpp \
    $$PWD/../../src/tucucore/drugmodel/validdose.cpp \
    $$PWD/../../src/tucucore/drugmodel/validduration.cpp \
    $$PWD/../../src/tucucore/sampleevent.cpp \
    $$PWD/../../src/tucucore/drugtreatment/sample.cpp \
    $$PWD/../../src/tucucore/drugtreatment/drugtreatment.cpp \
    $$PWD/../../src/tucucore/drugtreatment/target.cpp \
    $$PWD/../../src/tucucore/targetevent.cpp \
    $$PWD/../../src/tucucore/processingservice/processingrequest.cpp \
    $$PWD/../../src/tucucore/processingservice/processingresponse.cpp \
    $$PWD/../../src/tucucore/processingservice/iprocessingservice.cpp \
    $$PWD/../../src/tucucore/processingservice/processingtrait.cpp \
    $$PWD/../../src/tucucore/covariateevent.cpp

DISTFILES += \
    $$PWD/../../src/tucucore/makefile
